baseurl = "https://example.com/"
languageCode = "en-us"
theme = "hugo-theme-relearn"
pagination.pagerSize = 5

[markup.goldmark.renderer]
unsafe = true

[params]
showMenuItems = 2
fullWidthTheme = false
centerTheme = false
themeVariant = 'relearn-light'

[languages]
[languages.en]
title = "Spring skeleton"
copyright = ""

[languages.en.params.logo]
logoText = "Spring skeleton"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"