openapi: 3.1.0
info:
  title: Spring skeleton
  description: Swagger Spring skeleton
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /api/v1/survey:
    get:
      summary: Get all surveys
      description: Get all surveys
      operationId: getSurvey
      tags:
        - Survey
      responses:
        '200':
          description: A created survey
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SurveyDTO"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
    post:
      summary: Save survey
      description: Save survey
      operationId: postSurvey
      tags:
        - Survey
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SurveyDTO"
      responses:
        '200':
          description: A created survey
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SurveyDTO"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDTO"
components:
  schemas:
    SurveyDTO:
      type: object
      properties:
        enterpriseName:
          type: string
          description: Name of the enterprise that own survey
          example: Enterprise A
        name:
          type: string
          description: Name of the survey
          example: Survey A
        description:
          type: string
          description: Description of the survey
          example: Survey A description
        status:
          type: string
          description: Status of the survey. Accepted values are ACCEPTED / DECLINED
          example: ACCEPTED
        question:
          type: string
          description: Question of the survey
          example: Did you enjoy your trip ?
        options:
          oneOf:
            - $ref: "#/components/schemas/OpinionScaleDTO"
            - $ref: "#/components/schemas/GraduationDTO"
          discriminator:
            propertyName: type
            mapping:
              opinionScale: "#/components/schemas/OpinionScaleDTO"
              graduation: "#/components/schemas/GraduationDTO"
        votes:
          type: integer
          description: Votes of survey
    OpinionScaleDTO:
      type: object
      properties:
        type:
          type: string
        opinionScale:
          $ref: "#/components/schemas/OpinionScaleEnumDTO"
    OpinionScaleEnumDTO:
      type: array
      description: Options for the question in opinion scale format
      example: [ ABSOLUTELY_YES, YES, MAYBE, NO, ABSOLUTELY_NO ]
      items:
        type: string
        enum: [ ABSOLUTELY_YES, "YES", MAYBE, "NO", ABSOLUTELY_NO ]
        example: "YES"
    GraduationDTO:
      type: object
      properties:
        type:
          type: string
        graduation:
          type: array
          description: Options for the question in array of integer format
          items:
            type: integer
            minimum: 1
            maximum: 5
            example: 5
    ErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string